### PR TITLE
Added webpackDefinitions option

### LINKED ISSUE #42: Problem when using package formidable / node-formidable or anything that includes it, webpack doesn't compile the package correctly
As you can see on this thread
https://github.com/node-formidable/node-formidable/issues/337

node-formidable or other packages using it fail to compile correctly this line 
````
if (global.GENTLY) require = GENTLY.hijack(require);
````
creating 

````
var require;if (global.GENTLY) require = GENTLY.hijack(require);
````
this makes that later requires included are not properly transpiled and fail after deploy 
in the line var crypto = require("crypto")

the easiest workaround found in the thread is to add 
```
plugins: [
     new webpack.DefinePlugin({ "global.GENTLY": false })
], 
```

but that doesn't seem to be possible with this plugin. Any chance to allow custom webpack plugins or fix this problem?

### PR DESCRIPTION
**Pull request by tcastelli**
Fixes #42

Feel free to change naming if needed

### CODE REVIEW

**Comment by aureeaubert** [comment]
@jayair can you merge this pr asap? It's quite blocking for a lot of people. Thanks

**Comment by jayair** [comment]
@aureeaubert So far only @tcastelli has brought this up. And node-formidable is failing because it's using `require` that Webpack doesn't allow. It looks like their maintainers are trying to fix it as well - https://github.com/node-formidable/node-formidable/issues/337#issuecomment-579610313.

I'd like to know if there are other cases where these Webpack definitions are needed. What's the issue you are running into? Is it with node-formidable as well?

**Comment by Mulchek** [comment]
This would be a big help!

**Comment by kamarajuPrathi** [comment]
@jayair Can this pull request merged .. that would really help a lot .

**Comment by jayair** [comment]
@kamarajuPrathi @Mulchek Are you all running into the same issue with node-formidable?

**Comment by aureeaubert** [comment]
> @aureeaubert So far only @tcastelli has brought this up. And node-formidable is failing because it's using `require` that Webpack doesn't allow. It looks like their maintainers are trying to fix it as well - [node-formidable/formidable#337 (comment)](https://github.com/node-formidable/formidable/issues/337#issuecomment-579610313).
> 
> I'd like to know if there are other cases where these Webpack definitions are needed. What's the issue you are running into? Is it with node-formidable as well?

@jayair `node-formidable` as well, I don't understand why you don't want to merge it. I think having this feature can be very useful for other use cases too. Indeed, your library is currently too limited and I personally don't want to use the `serverless-webpack` as I don't want to waste time configuring a new webpack config every time I'm developing a new serverless project. It will be a pitty to have to clone your project just for this because for all the rest you did a great job

**Comment by jayair** [comment]
If everybody has an issue with `node-formidable`, does the proposed solution in their canary version not work? https://github.com/node-formidable/formidable/issues/337#issuecomment-579610313

@aureeaubert it doesn't make sense to merge this if the source of the problem is already being fixed right?

**Comment by patrykkrawczyk** [comment]
Can we merge this?
I'm writing a Lambda which uses `auth0` package. This package is using `superagent` which is using `formidable`. Since it's a nested dependency I cannot just use the canary version of formidable to get around this issue. This is super blocking for us :(.

**Comment by jayair** [comment]
@patrykkrawczyk @tcastelli @kamarajuPrathi @aureeaubert 

We've add some specific handling for formidable in [v1.4.0](https://github.com/AnomalyInnovations/serverless-bundle/releases/tag/v1.4.0). Add the following to your `serverless.yml`:

``` yml
custom:
  bundle:
    fixPackages:
      - "formidable@1.x"
```

Moving forward we want to handle specific packages in this way as well. Read more about it in the README.

Thanks for all the help!

**Comment by patrykkrawczyk** [comment]
Can confirm that this fixes issues with formidable as a transitive dependency, tested with Auth0 for Node.JS.

**Pull request closed without merging**
