### PR TITLE
Adding support for isomorphic style loading and dynamic file imports

### PR DESCRIPTION
**Pull request by PenguinOfWar**
Leveraging serverless-bundle to faciliate serverless rendering of a Create React App application I encountered an issue when loading styles imports and static files (e.g. logo images).

This patch adds two configuration options for `serverless.yml`

```
custom:
  bundle:
    cssImport: true
    fileLoader: true
```

### CODE REVIEW

**Comment by jayair** [comment]
Thanks for the PR. I'm wondering if we should default to having these options always on? Is there a downside to supporting these imports by default?

**Comment by PenguinOfWar** [comment]
> Thanks for the PR. I'm wondering if we should default to having these options always on? Is there a downside to supporting these imports by default?

None that I can think of, and it makes it more inline with the zero configuration aim of this project.

I've revised the pull request.

**Comment by jayair** [comment]
Awesome. Thank you. One last thing, can you give me some steps to test this?

**Comment by PenguinOfWar** [comment]
> Awesome. Thank you. One last thing, can you give me some steps to test this?

I've added an isomorphic loader test that covers the following cases:

- Import CSS
- Import SCSS/SASS
- Import image

I believe one test case to cover all three is sufficient, as this is the most likely use case when teaming serverless-bundle with something like Create React App.

@jayair As an additional point, would you consider implementing something like prettier in this project to look after code style? I was concerned while making the changes about stepping too far outside your code style or introducing inconsistencies.

**Comment by jayair** [comment]
Looks great thank you! https://github.com/AnomalyInnovations/serverless-bundle/releases/tag/1.5.0

I don't think we need `serverless` as a dependency, so I removed it. If this is a mistake let me know and I'll add it back.

I think I have prettier setup as a pre commit hook. Is it not working for you?

**Comment by PenguinOfWar** [comment]
Thanks for merging!

For serverless, I had to install it as I don’t have it installed as a global the specific version is scoped for the projects I’m working on. Sorry about that, forgot to remove it. 

For prettier, I didn’t see a .prettierrc and the pre-commit hook didn’t seem to fire. I’ll check this again when I’m next on my machine. It’s also my habit to just mash the format button before save and prettied kept defaulting to defaults. 

Thanks for the fast turnaround on the release, I’ll be able to move back to the serverless npm package on my projects.

**Pull request merged**
