### PR TITLE
Configurable minification

### PR DESCRIPTION
**Pull request by jurajmatus**
Issue #286

### CODE REVIEW

**Comment by carlswann** [comment]
Would love for this to get reviewed & merged soon :(

**Comment by H4ad** [comment]
@jayair Any update on this? I'm working on a PR to improve the NestJS serverless documentation and I really want to use this library, but I need to have this option enabled in order to be able to use the class validator and stuff.

**Comment by Cyberuben** [comment]
I'd like to see some progress here too. Any maintainer we can notify?

**Comment by jayair** [comment]
Can we add a quick test for this, document it in the README, and resolve the conflicts? I can merge it.

**Comment by jurajmatus** [comment]
@jayair Done, please review if okay

**Comment by jayair** [comment]
Merged! https://github.com/AnomalyInnovations/serverless-bundle/releases/tag/v5.5.0

**Comment by x3mka** [comment]
Thanks for the pull request. Please update the docs, minifyOptions should be an object, not array.

**Pull request merged**
