### PR TITLE
Adding permissions support

### LINKED ISSUE #92: Adding permissions support
Hi can you please add https://www.npmjs.com/package/webpack-permissions-plugin to have the fs support as well in the configuration. We use lots of files in the project and need it for the build to work.

### PR DESCRIPTION
**Pull request by ianpogi5**
Fixes #92

### CODE REVIEW

**Comment by ianpogi5** [comment]
At the moment this only works for `package.individually: false`.

I'm guessing it's because of the hardcoded `".webpack/service"` in my code.

**Comment by ianpogi5** [comment]
This now works for package individually. 

The test only covers the package individually. Should I also create for the reverse scenario?

**Comment by jayair** [comment]
Hi @ianpogi5 This looks pretty good. Thank you for the effort.

I agree, I think for completeness, let's add a test for the not individually packaged case. Just copy that test dir, rename and turn off that flag? Maybe have a `copy-files` and `copy-files-individually-packaged` case? You can name it either way.

And please mention me again, so I get notified. Again, appreciate the PR.

**Comment by ianpogi5** [comment]
@jayair No problem. I've added the other test.

**Comment by jayair** [comment]
Thank you! I'll cut a release shortly.

**Comment by jayair** [comment]
https://github.com/AnomalyInnovations/serverless-bundle/releases/tag/v4.2.2

**Comment by ianpogi5** [comment]
> https://github.com/AnomalyInnovations/serverless-bundle/releases/tag/v4.2.2

Thank you very much!

**Pull request merged**
