### PR TITLE
Upgrade dependencies to fix security issues within sub-dependencies

### LINKED ISSUE #374: Upgrade dependencies
Some of the dependencies within this package are marked with critical and high security issues. We should upgrade the dependencies to eliminate these.

### PR DESCRIPTION
**Pull request by gligorkot**
Fixes #374

### CODE REVIEW

**Comment by gligorkot** [comment]
@jayair, hope this is all good. I only upgraded the necessary dependencies to get the reported vulnerabilities back down to 0. It required quite a few test updates, so please have a look at those and merge at your convenience.

**Comment by jayair** [comment]
Yeah let's drop it. If you fix the test let me know, I'll cut a release.

**Comment by gligorkot** [comment]
@jayair all good. Dropped 14 and 16, CI should all pass now. Only thing that fails is the Label check, but I have no permissions to add labels, so that might have to be done by someone with permissions 🙏

**Comment by jayair** [comment]
Thanks!

**Comment by jayair** [comment]
Published https://github.com/AnomalyInnovations/serverless-bundle/releases/tag/v6.3.0

**Pull request merged**
