### PR TITLE
Add optimization.nodeEnv false to webpack config. Fixes #139.

### LINKED ISSUE #139: NODE_ENV being replace by wrong value
When `NODE_ENV` environment variable is set to `development` in the serverless config, the bundled lambda export replaces `process.env.NODE_ENV` with `production`. This is unexpected, I would expect it to be set to `development`. I wasn't able to find anything in the docs coving this. Is there a way to force it to use the value in the serverless config or disable `process.env` replacement?

severless.yml:
```yml
...
plugins:
  - serverless-bundle
...
custom:
  bundle:
    sourcemaps: false
    caching: false
    linting: false
...
provider:
  environment:  # Include dotenv above
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    NODE_ENV: ${opt:environment} # run as `development`
...

```
lambda.js
```js
...
const env = process.env.NODE_ENV // replaced with `production` instead of `development`
```

### PR DESCRIPTION
**Pull request by santiagomera**

### CODE REVIEW

**Comment by santiagomera** [comment]
Hi, sorry for the late reply, I just saw your comment.
I thought this was it, am I missing something?

**Comment by jayair** [comment]
Thanks, I'll check it out this weekend!

**Comment by elelha** [comment]
any idea why ci tests are failing?

**Review by elelha — APPROVED** [review]

**Comment by jayair** [comment]
Closes https://github.com/AnomalyInnovations/serverless-bundle/issues/139

**Pull request merged**
