### PR TITLE
Feature: support typescript project references

### PR DESCRIPTION
**Pull request by mfogel**
This PR adds support for [typescript project references](https://www.typescriptlang.org/docs/handbook/project-references.html).

To do so, it upgrades the following dependencies:
- `ts-loader` (to get https://github.com/TypeStrong/ts-loader/issues/1114)
- `fork-ts-checker-webpack-plugin` (to get https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/187)
- `eslint` (required by `fork-ts-checker-webpack-plugin` because of [this check](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/blob/v5.2.0/src/eslint-reporter/assertEsLintSupport.ts#L20-L24))

This PR includes a new test with a basic typescript monorepo configured with project references.

It's kinda a bummer the `eslint` upgrade is bundled into this PR. The only way I see around that would be to upgrade `eslint` & associated tools first as a separate step, and then address this PR/feature request.

Let me know if you'd like to see any fixes/changes or anything else I can do to help merge this in. Thanks a bunch for `serverless-bundle`, super helpful! Cheers.

### CODE REVIEW

**Comment by jayair** [comment]
Thanks for putting this together!

So from what I can see the main changes are to the `forkTsCheckerWebpackOptions`?

The rest of this change is just the ESLint major upgrade correct?

It sounds like we would need to do a major release for this change.

**Comment by jayair** [comment]
So we ended upgrading ESLint in this release.

https://github.com/AnomalyInnovations/serverless-bundle/releases/tag/v4.0.0

Might make it easier to now support this feature. Can you fix the conflicts and I'll have a look?

**Comment by mfogel** [comment]
Ah, great. That should simplify this PR a fair amount. I'll plan to update/rebase this PR on the latest on master over the weekend. Cheers

**Comment by mfogel** [comment]
@jayair PR has been updated, should merge cleanly now

**Comment by jayair** [comment]
Looks good!

**Comment by jayair** [comment]
Pushed a new release https://github.com/AnomalyInnovations/serverless-bundle/releases/tag/v4.1.0

**Pull request merged**
