### PR TITLE
Add support for .gql files

### LINKED ISSUE #58: Add support for graphql loaders?
Hello is there a way to add loader to support .graphql files?

### PR DESCRIPTION
**Pull request by mohamedGamalAbuGalala**
* Add graphql-tag/loader dependency
* Add loaders for gql/graphql files

vscode will complain because you do not handle this in a local webpack config file, but it works very well as its being loaded via serverless-bundle.

image

Fixes #58

### CODE REVIEW

**Comment by mohamedGamalAbuGalala** [comment]
Any updates on this??

**Comment by jayair** [comment]
Oh I missed this. Thank you for this. It looks good.

Before we merge it, can we add a very basic case showing that it can bundle `.gql` files?

Just copy this test case and the `tests/base/` directory — https://github.com/AnomalyInnovations/serverless-bundle/blob/master/tests/index.test.js#L17. Add a `.gql` file, import it in your `handler.js` and ensure that it can run the serverless command without throwing an error.

Let me know if you can do this, if not I'll have a look.

**Comment by jayair** [comment]
Thank you!

**Comment by rad182** [comment]
@mohamedGamalAbuGalala thanks for this!
Unfortunately when I try to create unit test still the graphql files isn't properly loaded.
image

@jayair any idea?

**Comment by mohamedGamalAbuGalala** [comment]
I still don't know how to tackle this, I'll Give It a shot and let you know :raised_hands:

**Comment by mohamedGamalAbuGalala** [comment]
I Had a workaround for the test issue, I abandon using loader from serverless-bundle after a lot of tries and wrote some script to read every `.gql` file as a string and concatenate them in one schema as #74 does.
but now you can say that serverless-bundle can't load .gql/.graphql files in the perfect way (Idk why).
you can load them in the developing and it will work but if you do either test/deploy it will not.

Sorry for the late response to this issue but I remember to do when I got a notification about a new Pr about the same issue with the same solution.

**Pull request merged**
