### PR TITLE
Conditional `forceExclude` of `aws-sdk` based on `runtime` version

### PR DESCRIPTION
**Pull request by cnuss**
On `nodejs18.x` and greater, `aws-sdk` is no longer included and should be conditionally excluded based on the `runtime` version, instead of being a hardcoded exclude.

Fixes: 
 - https://github.com/AnomalyInnovations/serverless-bundle/issues/364 
 - https://github.com/AnomalyInnovations/serverless-bundle/issues/353

Ref: https://stackoverflow.com/a/74792625

### CODE REVIEW

**Comment by cnuss** [comment]
cc @jayair could i get some 👀  on this please? thank you!

cc @warrickhill this is a similar fix to https://github.com/AnomalyInnovations/serverless-bundle/pull/354 but includes tests 😄, which I didn't actually see your pre-existing PR until after I did this work.

**Comment by cnuss** [comment]
Ok I tweaked this a bit so that the "default config" doesn't hardcode aws-sdk. It's now programatically _added_ in the event the runtime is less than `nodejs18.x`, which should be more future proof!

**Comment by augustl** [comment]
We currently use our own fork of serverless-bundle because of this. Good work, hope this gets merged!

**Comment by jayair** [comment]
Thank you for this (and adding the tests)!

**Pull request merged**
