### PR TITLE
Add support for webpack raw-loader

### PR DESCRIPTION
**Pull request by carlcheel**
Adds support for the raw-loader. Adds a config option so the user can defined which file exts are treated as raw files.

Resolves issue #33

### CODE REVIEW

**Comment by jayair** [comment]
@carlcheel This looks pretty good! Thank you for putting it together.

Just a thought, would it make sense to add some extensions in there by default? So `.pem` files or `.txt` files are handled automatically? Any other obvious files extensions that we could add?

**Comment by carlcheel** [comment]
Thank you @jayair 

Great idea. `.pem` and `.txt` are sensible defaults imo and guess it keeps the library as config-less as possible. 

I used it recently to import a `.html` file to use as an email template and following a quick Google, it looks like others may use it for this too. We could go with the following defaults initially?

- .pem
- .txt
- .html

What do you think?

**Comment by jayair** [comment]
Thank you!

I made a couple of tweaks. I think let's leave `.html` for now since there is a separate Webpack html-loader. And I just tweaked it so that if you specify the `rawFileExtensions` option, it'll concat it with the default list. Instead of overwriting it.

Published a new release — https://github.com/AnomalyInnovations/serverless-bundle/releases/tag/v1.9.0

**Comment by carlcheel** [comment]
No problem.

Awesome, that all makes sense to me. Issue #33 can be closed now too 🥳

**Pull request merged**
