### PR TITLE
Adds babel optional chaining

### PR DESCRIPTION
**Pull request by michaelwclark**
This is a must for many of our serverless environments. I was devistated to find out we couldn't configure this, so hopefully this is a quick PR to get this feature in.

### CODE REVIEW

**Comment by jayair** [comment]
Thanks for this! Can I ask you to add a test?

You can copy the `class-properties` dir — https://github.com/AnomalyInnovations/serverless-bundle/tree/master/tests/class-properties

And add the syntax that uses optional chaining in the `handler.js`.

**Comment by michaelwclark** [comment]
Yea I'll get some tests added early next week. Thanks for the quick turnaround.

**Comment by michaelwclark** [comment]
@jayair Sorry about delay. I forgot about this until i needed it!  I got the test updated and working but eslint hates me. `2:13  error  Parsing error: Unexpected token ;` seems easy to fix, but i spent more time than i care to admit on it. If you don't know a quick fix let me know and i'll spend more time on it as I'm able.

**Comment by michaelwclark** [comment]
I see travis passed, maybe it was a local issue on my end.

**Comment by jayair** [comment]
Awesome! Thank you. I'll merge this and release it shortly.

**Comment by jayair** [comment]
Pushed a new release.

https://github.com/AnomalyInnovations/serverless-bundle/releases/tag/v4.0.0

**Pull request merged**
